"""create game rooms

Revision ID: 531683c83e2a
Revises: b45c1c0e1136
Create Date: 2026-08-08 11:39:00.886901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531683c83e2a'
down_revision: Union[str, Sequence[str], None] = 'b45c1c0e1136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_rooms_id'), 'game_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_game_rooms_room_code'), 'game_rooms', ['room_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_rooms_room_code'), table_name='game_rooms')
    op.drop_index(op.f('ix_game_rooms_id'), table_name='game_rooms')
    op.drop_table('game_rooms')
    # ### end Alembic commands ###
