"""add player ready states

Revision ID: c9ab1f364d1e
Revises: 531683c83e2a
Create Date: 2026-08-08 16:28:35.443615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ab1f364d1e'
down_revision: Union[str, Sequence[str], None] = '531683c83e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'game_rooms',
    sa.Column(
        'host_ready',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )
    )

    op.add_column(
            'game_rooms',
            sa.Column(
                'guest_ready',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false')
            )
        )
            # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_rooms', 'guest_ready')
    op.drop_column('game_rooms', 'host_ready')
    # ### end Alembic commands ###
